import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#51358f",
        "error": "#ba1a1a",
        "surface-dim": "#e9d5d8",
        "tertiary-fixed": "#94f996",
        "surface-bright": "#fff8f8",
        "surface-tint": "#a4355d",
        "on-secondary-fixed": "#24005b",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#00350c",
        "on-primary-fixed": "#3f001b",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#554246",
        "on-primary-fixed-variant": "#851c45",
        "on-secondary": "#ffffff",
        "secondary": "#694da9",
        "on-secondary-container": "#4c2f89",
        "surface": "#fff8f8",
        "primary-fixed-dim": "#ffb1c5",
        "outline": "#887176",
        "on-primary": "#ffffff",
        "surface-container-low": "#fff0f2",
        "surface-container": "#fde9ec",
        "primary-fixed": "#ffd9e1",
        "on-tertiary-fixed": "#002105",
        "inverse-surface": "#392d30",
        "primary-container": "#e86a92",
        "tertiary-fixed-dim": "#79dc7d",
        "on-surface": "#23191b",
        "primary": "#a4355d",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#ffb1c5",
        "secondary-container": "#bb9eff",
        "background": "#ffffff",
        "secondary-fixed": "#eaddff",
        "secondary-fixed-dim": "#d1bcff",
        "on-background": "#23191b",
        "inverse-on-surface": "#ffecef",
        "tertiary-container": "#45a74f",
        "on-tertiary-fixed-variant": "#005317",
        "surface-variant": "#f2dee1",
        "surface-container-highest": "#f2dee1",
        "surface-container-high": "#f7e3e6",
        "on-primary-container": "#5f002b",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "tertiary": "#006e22",
        "outline-variant": "#dbc0c5",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        gutter: "32px",
        "margin-tablet": "40px",
        "margin-mobile": "24px",
        "section-gap": "120px",
        "container-max": "1440px",
        "component-gap": "24px",
        "margin-desktop": "80px",
      },
      maxWidth: {
        "container-max": "1440px",
      },
      fontFamily: {
        "display": ["Playfair Display", "serif"],
        "headline": ["Playfair Display", "serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
        "display-md": ["48px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      boxShadow: {
        editorial: "0px 20px 40px rgba(0,0,0,0.04)",
        "editorial-md": "0px 8px 24px rgba(0,0,0,0.06)",
      },
      keyframes: {
        fadeInUp: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "fade-in-up": "fadeInUp 0.6s ease-out forwards",
      },
    },
  },
  plugins: [],
};

export default config;
